### ISSUE TITLE
Install WebArchiveReader from Package Manger Console failed

### ISSUE THREAD

**Issue by zhmxx** [Sicos1977/WebArchiveExtractor#1]
I tried to install WebArchiveReader from Package Manager Console in VS2015 with command:
`Install-Package WebArchiveReader `

It failed with error:
	
> Install-Package : Unable to find package 'WebArchiveExtractor'
	At line:1 char:1
	+ Install-Package WebArchiveExtractor
	+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		+ CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
		+ FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

Why did I get this error?

**Comment by Sicos1977** [comment]
This is still work in progress :-) .. see the readme on the main page

WORK IN PROGRESS.. THIS IS NON WORKING CODE !!

I'll try to make the code work this or next week.

There is no nuget package yet. I only did setup the GitHub project and did some programming. Didn't except that someone would find this project this soon.

**Comment by zhmxx** [comment]
Didn't notice the headline.. :sweat_smile: Looking forward to it.

**Comment by Sicos1977** [comment]
There is a working version on GitHub, you can give it a try if you want. I still need to add more logging and do a lott of tweakings here and there. Please let me know how this version works for you.

**Comment by Sicos1977** [comment]
I just released a first version.

https://www.nuget.org/packages/WebArchiveExtractor/
